source:       .
destination:  ./_site
include:      []
exclude:      [CNAME, Gemfile, Gemfile.lock, pom.xml, txazoc-github-io.iml, README.md, push.sh, script]
timezone:     Asia/Shanghai
encoding:     UTF-8

permalink:  /:categories/:title.html

gems: [jekyll-paginate]

# 网站设置
title: "txazoc"
email: "txazo1218@163.com"
description: "java,openjdk,jvm,java web,设计模式,开源框架,struts2,spring,mybatis,数据库,mysql,linux,html,css,js,javascript,jquery,ruby,python,shell"
baseurl: ""
url: "http://www.txazo.com"

# Markdown引擎
# kramdown, maruku, rdiscount, redcarpet
markdown:      rdiscount
markdownStyle: md-primary

# highlight高亮样式
highlightstyle: hljs-txazo

# 是否本地调试
localDebug: "false"

# 本地域名
localDomain: "http://127.0.0.1:4000"
# 源站域名
sourceDomain: "http://www.txazo.com"
# 首页加速域名
indexSpeedDomain: 'http://www.txazo.com'
# 静态加速域名
staticSpeedDomain: 'http://www.txazo.com'

# 百度统计开关
hmSwitch: "true"
# Google Analytics开关
gaSwitch: "false"

# css引入
css: ["http://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css", "http://www.txazo.com/css/core.css"]
localCss: ["/css/lib/bootstrap.min.css", "/css/core.css"]
# js引入
js: ["http://cdn.bootcss.com/jquery/1.12.1/jquery.min.js", "http://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js", "http://cdn.bootcss.com/seajs/3.0.2/sea.js", "http://www.txazo.com/js/lib/seajs-css.js", "http://cdn.bootcss.com/highlight.js/9.5.0/highlight.min.js", "http://www.txazo.com/js/load.js"]
localJs: ["/js/lib/jquery.min.js", "/js/lib/bootstrap.min.js", "/js/lib/sea.js", "/js/lib/seajs-css.js", "/js/lib/highlight.min.js", "/js/load.js"]

# rss
rssxml: "/feed.xml"

# 导航条菜单
menu:
    首页: /
    标签: /tag.html
    归档: /archive.html
    专题: /topics.html
    关于: /about.html

# 分页
paginate: 10
paginate_path: "index/:num"
