source:       .
destination:  ./_site
include:      []
exclude:      [CNAME, Gemfile, Gemfile.lock, pom.xml, txazo-github-io.iml]
timezone:     Asia/Shanghai
encoding:     UTF-8

permalink:  /:categories/:title.html

gems: [jekyll-paginate]

# 网站设置
title: "txazoc"
email: "txazo1218@163.com"
description: "java,openjdk,jvm,java web,设计模式,开源框架,struts2,spring,mybatis,数据库,mysql,linux,html,css,js,javascript,jquery"
baseurl: ""
url: "http://www.txazo.com"

# Markdown引擎
# kramdown, maruku, rdiscount, redcarpet
markdown:      rdiscount
markdownStyle: md-primary

# highlight高亮样式
highlightstyle: hljs-txazo

# css引入
css: ["http://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css", "/css/core.css"]
# js引入
js: ["http://cdn.bootcss.com/jquery/1.12.1/jquery.min.js", "http://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js", "http://cdn.bootcss.com/seajs/3.0.2/sea.js", "http://cdn.bootcss.com/highlight.js/9.5.0/highlight.min.js", "/js/load.js"]

# rss
rssxml: "/feed.xml"

# 导航条菜单
menu:
    首页: /
    标签: /tag.html
    归档: /archive.html
    关于: /about.html

focus:
    email: "mailto:txazo1218@163.com"
    facebook: "https://www.facebook.com/txazo"
    twitter: "https://twitter.com/txazo1218"
    github: "https://github.com/txazo"
    rss: "/feed.xml"
    weibo: "http://weibo.com/txazo"
    qzone: "javascript:;"
    weixin: "javascript:;"

# 分页
paginate: 10
paginate_path: "index/:num"
